FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Orders.Frontend/Orders.Frontend.csproj", "Orders.Frontend/"]
COPY ["Orders.Shared/Orders.Shared.csproj", "Orders.Shared/"]
RUN dotnet restore "Orders.Frontend/Orders.Frontend.csproj"
COPY . .
WORKDIR "/src/Orders.Frontend"
RUN dotnet publish "Orders.Frontend.csproj" -c Release -o /app/publish

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/publish/wwwroot .
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
